### ISSUE TITLE
EPIC: Search and Sort Products

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/depo-pc#11]
**Description:** This epic focuses on enhancing the search and sorting capabilities within the depoPC e-commerce platform, providing users with a more personalized and efficient shopping experience.

**Additional Information:**
- Design a clean and intuitive UI for the search bar and filter/sort options to enhance the overall user experience.

**Linked User Stories:**
- [x] #19 As a shopper, I want to perform a search by keywords so that I can quickly find specific products based on my preferences.
- [x] #20 As a shopper, I want to filter search results by category, price range, and other relevant criteria so that I can narrow down my options.
- [x] #21 As a shopper, I want to filter after multiple categories simultaneously
- [x] #22 As a shopper, I want to view the products that I have searched for, so that I can quickly assess if the items meets my requirements.
