### ISSUE TITLE
EPIC: Favorites

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/depo-pc#29]
**Description:** Effortlessly create, manage, and personalize a favorites list for future shopping endeavors. Easily add, remove, and track preferred products, enhancing the user's shopping experience.

**Additional Information:**
- Users can easily add and remove items from their favorites list.
- The favorites list provides a convenient way for users to track price changes, discounts, or availability of their preferred products.

**Linked User Stories:**
- [x] #30 As a shopper, I want to add products to my favorites list, so that I can save them for future consideration.
- [x] #31 As a shopper, I want to remove products from my favorites list, in case my preferences change.
- [x] #32 As a shopper, I want to view my favorites list, so that I can see the list of products I've saved.
