### ISSUE TITLE
USER STORY: Remove Products from the Favorite list

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/depo-pc#31]
Epic: #29 

As a **shopper**, I want **to remove products from my favorite list, in case my preferences change.**

**Tasks**
- [x] Navigate to the favorite list section of the website.
- [x] Identify the product I want to remove.
- [x] Click on the "Remove" or similar option next to the product.
- [x] Successful message displayed

**Acceptance Criteria**
- The product should be successfully removed from the shopper's Favorite list.
