### ISSUE TITLE
USER STORY: Add Review section

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/depo-pc#35]
Epic: #10 

As a ** customer **, I can ** add a review for a product ** so that ** I can share my feedback with other users **.

**Tasks**
- [x] Implement a form for adding a review.
- [x] Create a modal dialog for adding a review.
- [x] Update the product details page to include the "Add review" button and modal trigger.
- [x] Handle form submission to add the review to the database.

**Acceptance Criteria**
- The product details page should display an "Add review" button.
- Clicking on the "Add review" button should open a modal dialog.
- The modal dialog should have field for entering the comment.
- After submitting the review form, the review should be added to the database.
- The review should be associated with the logged-in user and the respective product.
