### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/depo-pc#7]
Epic: #6 

As a **user**, I want **a homepage with relevant information and options** so that **I can quickly access the latest updates and find useful content**.

**Tasks**
- [x] Create the Home Page
- [x] Display relevant content
- [x] Include clear navigation options

**Acceptance Criteria**
- Users see a well designed homepage
- The content is relevant
- User-friendly navigation
